### ISSUE TITLE
Appstream 2.0 and Windows Folder Directory

### ISSUE THREAD

**Issue by randpow** [aws-samples/moodle-mod_appstream#1]
Hi,

i realized that the Windows folder directory (C:\Users\PhotonUser\My Files\Home) mapped to S3 User Home Folder, sometimes is different (i.e. C:\Users\PhotonUser XX-XXXXXX\My Files\Home). My application point to this windows directory to load files and projects, but it can´t access if the windows directory changes.

Is there any workaround or way to solve this?

Thanks in advance.

Alberto

**Comment by brianjbeach** [comment]
Try the HOMEPATH environment variable.

**Comment by randpow** [comment]
Thank you for your response.

So you mean, i can define HOMEPATH=C:\HomeFolder (i.e) and any session in Appstream will map this directory to S3 User Folder. Am I right?

Thank you in advance
